// 📄 FILE: src/pages/CookiePolicy.jsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import Footer from '../components/Footer';
import '../styles/LegalPages.css';

const CookiePolicy = () => {
  const navigate = useNavigate();

  return (
    <>
      <Helmet>
        <title>Cookie Policy | Beverage.fyi</title>
        <link rel="canonical" href="https://beverage.fyi/cookies" />
      </Helmet>
      
      <div className="legal-page">
        <main className="legal-content">
          <div className="legal-container">
            <button 
              className="back-button"
              onClick={() => navigate(-1)}
              aria-label="Go back"
            >
              ← Back
            </button>

            <h1 className="legal-title">Cookie Policy</h1>
            <p className="legal-updated">Last Updated: October 2025</p>

            <section className="legal-section">
              <h2>1. Introduction</h2>
              <p>
                This Cookie Policy explains how Beverage.fyi ("we," "us," or "our") uses cookies and 
                similar tracking technologies when you visit our website. This policy provides you with 
                clear and comprehensive information about the cookies we use and the purposes for using them.
              </p>
            </section>

            <section className="legal-section">
              <h2>2. What Are Cookies?</h2>
              <p>
                Cookies are small text files that are placed on your computer or mobile device when you 
                visit a website. They are widely used to make websites work more efficiently and provide 
                information to the site owners. Cookies allow websites to recognize your device and store 
                some information about your preferences or past actions.
              </p>
            </section>

            <section className="legal-section">
              <h2>3. How We Use Cookies</h2>
              <p>
                Beverage.fyi uses cookies primarily for analytics purposes to understand how visitors 
                interact with our website. This helps us improve our content and user experience. We use 
                cookies to:
              </p>
              <ul className="legal-list">
                <li>Understand how visitors navigate through our website;</li>
                <li>Analyze which pages are most frequently visited;</li>
                <li>Identify technical issues or areas for improvement;</li>
                <li>Measure the effectiveness of our content;</li>
                <li>Improve overall website performance and user experience.</li>
              </ul>
            </section>

            <section className="legal-section">
              <h2>4. Types of Cookies We Use</h2>
              
              <h3>Analytics Cookies</h3>
              <p>
                We use analytics cookies to collect information about how visitors use our website. 
                These cookies collect information in an aggregated form to help us understand how our 
                website is being used and how effective our content is. The information collected includes:
              </p>
              <ul className="legal-list">
                <li>Number of visitors to the site;</li>
                <li>Pages visited and time spent on each page;</li>
                <li>Traffic sources (where visitors came from);</li>
                <li>Browser and device information;</li>
                <li>General geographic location (country/city level).</li>
              </ul>

              <h3>Session Cookies</h3>
              <p>
                These are temporary cookies that expire when you close your browser. They help our 
                website remember your actions during a single browsing session.
              </p>

              <h3>Persistent Cookies</h3>
              <p>
                These cookies remain on your device for a set period or until you delete them. They 
                help us recognize you as a returning visitor and remember your preferences.
              </p>
            </section>

            <section className="legal-section">
              <h2>5. Third-Party Cookies</h2>
              
              <h3>Google Analytics</h3>
              <p>
                We use Google Analytics, a web analytics service provided by Google LLC. Google Analytics 
                uses cookies to help us analyze how users interact with our website. The information 
                generated by the cookie about your use of the website (including your IP address) will be 
                transmitted to and stored by Google on servers in the United States.
              </p>
              <p>
                Google will use this information for the purpose of evaluating your use of the website, 
                compiling reports on website activity for website operators, and providing other services 
                relating to website activity and internet usage. Google may also transfer this information 
                to third parties where required to do so by law, or where such third parties process the 
                information on Google's behalf.
              </p>
              <p>
                For more information about how Google uses data when you use our website, please visit:{' '}
                <a 
                  href="https://policies.google.com/technologies/partner-sites" 
                  className="legal-link"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  How Google uses information from sites or apps that use our services
                </a>
              </p>
            </section>

            <section className="legal-section">
              <h2>6. Your Cookie Choices</h2>
              <p>
                You have several options for managing and controlling cookies:
              </p>

              <h3>Browser Settings</h3>
              <p>
                Most web browsers allow you to control cookies through their settings preferences. You can 
                set your browser to refuse cookies or delete certain cookies. Generally, you can also manage 
                similar technologies in the same way that you manage cookies – using your browser's preferences.
              </p>
              <p>
                Please note that if you choose to block cookies, some features of our website may not 
                function properly or may be unavailable to you.
              </p>

              <h3>Google Analytics Opt-Out</h3>
              <p>
                You can opt out of Google Analytics tracking by installing the Google Analytics Opt-out 
                Browser Add-on. This add-on instructs the Google Analytics JavaScript not to send information 
                to Google Analytics. To opt out of Google Analytics, visit:{' '}
                <a 
                  href="https://tools.google.com/dlpage/gaoptout" 
                  className="legal-link"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Google Analytics Opt-out Browser Add-on
                </a>
              </p>

              <h3>Browser-Specific Instructions</h3>
              <p>For detailed information on how to manage cookies in popular browsers, please visit:</p>
              <ul className="legal-list">
                <li>
                  <strong>Chrome:</strong>{' '}
                  <a 
                    href="https://support.google.com/chrome/answer/95647" 
                    className="legal-link"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Chrome Cookie Settings
                  </a>
                </li>
                <li>
                  <strong>Firefox:</strong>{' '}
                  <a 
                    href="https://support.mozilla.org/en-US/kb/cookies-information-websites-store-on-your-computer" 
                    className="legal-link"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Firefox Cookie Settings
                  </a>
                </li>
                <li>
                  <strong>Safari:</strong>{' '}
                  <a 
                    href="https://support.apple.com/guide/safari/manage-cookies-sfri11471/mac" 
                    className="legal-link"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Safari Cookie Settings
                  </a>
                </li>
                <li>
                  <strong>Edge:</strong>{' '}
                  <a 
                    href="https://support.microsoft.com/en-us/microsoft-edge/delete-cookies-in-microsoft-edge-63947406-40ac-c3b8-57b9-2a946a29ae09" 
                    className="legal-link"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Edge Cookie Settings
                  </a>
                </li>
              </ul>
            </section>

            <section className="legal-section">
              <h2>7. Do Not Track Signals</h2>
              <p>
                Some browsers include a "Do Not Track" (DNT) feature that signals to websites that you 
                visit that you do not want to have your online activity tracked. At this time, we do not 
                respond to DNT signals. This is consistent with the current state of technology, as there 
                is no industry standard for how to respond to DNT signals.
              </p>
            </section>

            <section className="legal-section">
              <h2>8. Cookies and Personal Information</h2>
              <p>
                The cookies we use do not collect personal information that identifies you individually. 
                Analytics cookies collect information about your browsing behavior in an aggregated and 
                anonymized format. We do not use cookies to collect sensitive personal information such 
                as names, email addresses, or financial information.
              </p>
            </section>

            <section className="legal-section">
              <h2>9. Children's Privacy</h2>
              <p>
                Our website is not directed to children under the age of 13, and we do not knowingly 
                collect information from children under 13 through cookies or any other means. If you 
                are under 13, please do not provide any information on this website.
              </p>
            </section>

            <section className="legal-section">
              <h2>10. Changes to This Cookie Policy</h2>
              <p>
                We may update this Cookie Policy from time to time to reflect changes in our practices 
                or for other operational, legal, or regulatory reasons. We will notify you of any material 
                changes by posting the updated policy on this page with a new "Last Updated" date. We 
                encourage you to review this Cookie Policy periodically to stay informed about how we 
                use cookies.
              </p>
            </section>

            <section className="legal-section">
              <h2>11. More Information</h2>
              <p>
                For more information about our privacy practices and how we handle your personal data, 
                please review our{' '}
                <a href="/privacy" className="legal-link">Privacy Policy</a>.
              </p>
            </section>

            <section className="legal-section">
              <h2>12. Contact Us</h2>
              <p>
                If you have any questions about our use of cookies or this Cookie Policy, please contact us at:
              </p>
              <p>
                <strong>Beverage.fyi</strong><br />
                Email: <a href="mailto:derekengles@gmail.com" className="legal-link">derekengles@gmail.com</a>
              </p>
            </section>
          </div>
        </main>

        {/* Desktop Footer */}
        <div className="desktop-only">
          <Footer />
        </div>
      </div>
    </>
  );
};

export default CookiePolicy;